# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: jasontestapp216.herokuapp.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: jasonchang216@gmail.com
  secret_key_base: ba7c6619472541c7162acc36df519e80184bba3683f89ef4ec4f75241368bd68ff8c5ad78becf241050349ac81975ed87597f16eba7a080618415c67fae64277

test:
  secret_key_base: 9dd4b25f18a0aeba38cc7489a14ae5a6ec0b6b7b0882d585f0af2671d0936497a5ebfceaf09dcb66038a4646c2918e7537458c8c6d13e82c062b8f080980b6c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: reperch.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: jasonchang216@gmail.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
